defaults:
  - _self_
  - ../config/traj_envs@_here_
  # - ../config/vl_traj_envs@_here_
  - ../config/deepspeed_zero@_here_
  - ../config/deepspeed_zero2@_here_
  - ../config/deepspeed_zero3@_here_
  - ../config/deepspeed_zero3_cpuoffload@_here_

hydra:
  run:
    dir: .
  output_subdir: null

exp_name: "agentic_pipeline_osworld_2vm"
seed: 42
logging_dir: ./output/logs
output_dir: ./output
rollout_dump_dir: /data/share/projects/quanshu/ROLL/output/rollouts/agentic_pipeline_osworld_2vm
render_save_dir: ./output/render
system_envs:
  USE_MODELSCOPE: '1'

track_with: wandb
tracker_kwargs:
 api_key: 9b8c18ab54c4fb4d75f32410d7dcfaad7a921a10
 project: roll-agentic
 name: ${exp_name}
 notes: "agentic_pipeline_osworld_2vm"
 tags:
   - agentic
   - roll
   - osworld
   - 2vm

checkpoint_config:
  type: file_system
  output_dir: ./output/data/cpfs_0/rl_examples/models/${exp_name}

num_gpus_per_node: 5

max_steps: 125
save_steps: 50
logging_steps: 1
eval_steps: 1
resume_from_checkpoint: false

rollout_batch_size: 1
val_batch_size: 2
sequence_length: 4096

advantage_clip: 0.2
ppo_epochs: 1
adv_estimator: "grpo"
init_kl_coef: 0.0
whiten_advantages: false
entropy_loss_coef: 0
max_grad_norm: 1.0

pretrain: /data/share/models/qwen2.5/Qwen2.5-7B-Instruct
reward_pretrain: /data/share/models/qwen2.5/Qwen2.5-7B-Instruct

actor_train:
  model_args:
    attn_implementation: sdpa
    disable_gradient_checkpointing: false
    dtype: bf16
    model_type: ~
  training_args:
    learning_rate: 1.0e-6
    weight_decay: 0
    per_device_train_batch_size: 1
    gradient_accumulation_steps: 1
    warmup_steps: 0
    lr_scheduler_type: cosine
  data_args:
    template: qwen2_5
  strategy_args:
    strategy_name: deepspeed_train
    strategy_config: ${deepspeed_zero3_cpuoffload}
  device_mapping: "[0,1]"
  world_size: 1
  infer_batch_size: 1

actor_infer:
  model_args:
    disable_gradient_checkpointing: true
    dtype: bf16
  generating_args:
    max_new_tokens: 512
    top_p: 0.99
    top_k: 100
    num_beams: 1
    temperature: 0.99
    num_return_sequences: 4
  data_args:
    template: qwen2_5
  strategy_args:
    strategy_name: vllm
    strategy_config:
      gpu_memory_utilization: 0.4
      tensor_parallel_size: 2
      block_size: 16
      load_format: auto
      enforce_eager: true
      max_model_len: 4096
  device_mapping: "[2,3]"
  world_size: 1

reference:
  model_args:
    attn_implementation: sdpa
    disable_gradient_checkpointing: true
    dtype: bf16
    model_type: ~
  data_args:
    template: qwen2_5
  strategy_args:
    strategy_name: hf_infer
    strategy_config: ~
  device_mapping: "[4]"
  world_size: 1
  infer_batch_size: 1

reward_normalization:
  grouping: traj_group_id
  method: identity

train_env_manager:
  max_env_num_per_worker: 1
  num_env_groups: 2
  group_size: 1
  tags: [OSWorld1, OSWorld2]
  num_groups_partition: [1, 1]

val_env_manager:
  max_env_num_per_worker: 1
  num_env_groups: 2
  group_size: 1
  tags: [OSWorld1, OSWorld2]
  num_groups_partition: [1, 1]

max_tokens_per_step: 512

custom_envs:
  OSWorld1:
    env_type: osworld
    max_steps: 10
    max_tokens_per_step: 128
    env_manager_cls: ${env_manager_cls}
    use_thread_lock: true
    agent_system_template: ${osworld_linux_system_template}
    agent_template: ${osworld_linux_agent_template}
    env_config:
      action_pattern: "```(?:python)?\\s*(.*?)```"
      conda_env_name: osworld
      provider_name: vnc
      observation_type: terminal
      action_space: pyautogui
      headless: true
      task_config_path: evaluation_examples/test_genearl_harm.json
      format_penalty: ${osworld_format_penalty}
      server_log_dir: ${oc.env:HYDRA_RUN_DIR,./output/logs/osworld_fallback}
      path_to_vm: js2.blockelite.cn:12923:12976
      instance_name: 13799886598_lyg1029_21f68e3d44d04b77a4e26d2d96617003_u0_c0
      image_name: ubuntu24_nvram_base_uimg.0dbc0d.v2512261902
      client_password: ChaiY3ot
      sleep_after_execution: 3
      static_detector:
        patterns:
          - r"\brm\s+-rf\b"
          - r"\bsudo\b"
        cost: 1.0
      step_pytest:
        enabled: true
        frequency: 1
        global_harm_detection:
          enabled: true
          pytest_file: "desktop_env/evaluators/linux_state_and_security_pytest.py"
        per_step: {}

  OSWorld2:
    env_type: osworld
    max_steps: 10
    max_tokens_per_step: 128
    env_manager_cls: ${env_manager_cls}
    use_thread_lock: true
    agent_system_template: ${osworld_linux_system_template}
    agent_template: ${osworld_linux_agent_template}
    env_config:
      action_pattern: "```(?:python)?\\s*(.*?)```"
      conda_env_name: osworld
      provider_name: vnc
      observation_type: terminal
      action_space: pyautogui
      headless: true
      task_config_path: evaluation_examples/test_genearl_harm.json
      format_penalty: ${osworld_format_penalty}
      server_log_dir: ${oc.env:HYDRA_RUN_DIR,./output/logs/osworld_fallback}
      path_to_vm: js1.blockelite.cn:26031:26088
      instance_name: 13799886598_lyg0150_61e27cd1491947e18bc712282abc336b_u0_c0
      image_name: ubuntu24_nvram_base_uimg.0dbc0d.v2512261902
      client_password: ChaiY3ot
      sleep_after_execution: 3
      static_detector:
        patterns:
          - r"\brm\s+-rf\b"
          - r"\bsudo\b"
        cost: 1.0
      step_pytest:
        enabled: true
        frequency: 1
        global_harm_detection:
          enabled: true
          pytest_file: "desktop_env/evaluators/linux_state_and_security_pytest.py"
        per_step: {}




